# Generated by Django 4.1.1 on 2022-09-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.SmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PCikAndCusip",
            fields=[
                ("report_date", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "cik",
                    models.CharField(
                        blank=True, max_length=120, primary_key=True, serialize=False
                    ),
                ),
                ("cusip", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.CharField(blank=True, max_length=6, null=True)),
                ("cusip6", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "p_cik_and_cusip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PCikmap",
            fields=[
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("report_date", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "cik",
                    models.CharField(
                        blank=True, max_length=15, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "p_cikmap",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PCikTicker",
            fields=[
                (
                    "cik",
                    models.CharField(
                        blank=True, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("ticker", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "p_cik_ticker",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PCikToCusip",
            fields=[
                (
                    "cik",
                    models.CharField(
                        blank=True, max_length=120, primary_key=True, serialize=False
                    ),
                ),
                ("cusip", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.CharField(blank=True, max_length=6, null=True)),
                ("cusip6", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "p_cik_to_cusip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PComByInd",
            fields=[
                (
                    "commodity",
                    models.CharField(
                        blank=True, max_length=200, primary_key=True, serialize=False
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=200, null=True)),
                ("value", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "commodity_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "industry_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "p_com_by_ind",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PForm13F",
            fields=[
                (
                    "cik",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("cusip", models.CharField(blank=True, max_length=50, null=True)),
                ("shares", models.CharField(blank=True, max_length=50, null=True)),
                ("report_date", models.CharField(blank=True, max_length=50, null=True)),
                ("file_date", models.CharField(blank=True, max_length=50, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "p_form13f",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PSicToNaics",
            fields=[
                (
                    "sic",
                    models.CharField(
                        blank=True, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("sic_desc", models.CharField(blank=True, max_length=200, null=True)),
                ("naics", models.CharField(blank=True, max_length=20, null=True)),
                ("naics_desc", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "p_sic_to_naics",
                "managed": False,
            },
        ),
    ]
