# Generated by Django 4.1.1 on 2022-10-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppleTest",
            fields=[
                (
                    "cik",
                    models.CharField(
                        blank=True, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("shares", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "report_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "apple_test",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BeaCommodity",
            fields=[
                (
                    "commodity_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("commodity", models.CharField(blank=True, max_length=50, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "bea_commodity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BeaIndustry",
            fields=[
                (
                    "industry_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=50, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "bea_industry",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cik",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("short_cik", models.CharField(blank=True, max_length=15, null=True)),
                ("investor", models.CharField(blank=True, max_length=500, null=True)),
                ("long_cik", models.CharField(blank=True, max_length=15, null=True)),
                ("ticker", models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                "db_table": "cik",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cusip",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("long_cik", models.CharField(blank=True, max_length=15, null=True)),
                ("sec_name", models.CharField(blank=True, max_length=500, null=True)),
                ("issuance", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "issuance_desc",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "cusip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Dates",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("form_date", models.CharField(blank=True, max_length=20, null=True)),
                ("year", models.CharField(blank=True, max_length=5, null=True)),
                ("day", models.CharField(blank=True, max_length=5, null=True)),
                ("month", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "db_table": "dates",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FileType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_type", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "file_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Form13F",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("shares", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "form13f",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IndustryValues",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "industry_values",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SicNaics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sic", models.CharField(blank=True, max_length=10, null=True)),
                ("sic_desc", models.CharField(blank=True, max_length=100, null=True)),
                ("naics", models.CharField(blank=True, max_length=20, null=True)),
                ("naics_desc", models.CharField(blank=True, max_length=200, null=True)),
                ("sec_code", models.CharField(blank=True, max_length=5, null=True)),
                ("sec_desc", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "sec_sub_desc",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
            options={
                "db_table": "sic_naics",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="PCikAndCusip",
        ),
        migrations.DeleteModel(
            name="PCikmap",
        ),
        migrations.DeleteModel(
            name="PCikTicker",
        ),
        migrations.DeleteModel(
            name="PCikToCusip",
        ),
        migrations.DeleteModel(
            name="PComByInd",
        ),
        migrations.DeleteModel(
            name="PForm13F",
        ),
        migrations.DeleteModel(
            name="PSicToNaics",
        ),
    ]
