# Generated by Django 4.1.1 on 2022-10-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_appletest_beacommodity_beaindustry_cik_cusip_dates_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppleTest",
        ),
    ]
